execution_strategy=remote
browser=chrome
internal_uat_url=https://apac.dev.poems.refinitiv.com/billing/
baseUrl=https://apac.dev.poems.refinitiv.com/billing/
username=paul.nate
password=1234
rememberMe=true
dbUser = billing
dbPassword = password
dbUrl=jdbc:postgresql://127.0.0.1:5434/billing